sauce_connect: true
browsers:
  - name: chrome
    version: -2..latest
  - name: firefox
    version: -2..latest
  - name: safari
    version: 8..latest
  - name: MicrosoftEdge
    version: -2..latest
  - name: ie
    version: 11
  - name: iphone
    version: '10.3..latest'
  - name: android
    version: '6.0..latest'
server: ./test/server/index.js
scripts:
  - "/test-polyfill.js"
browserify:
  - options:
      dedupe: false
